updated readme and cleaned up script

diff --git a/naisplater/naisplater b/naisplater/naisplater
--- a/naisplater/naisplater
+++ b/naisplater/naisplater
@@ -1,53 +1,76 @@
 #!/bin/bash
+#
+# util for processing golang templates
 
 ENV="${1}"
-OUTPUT_DIR="out"
-VARS_DIR="vars"
+TEMPLATES_DIR="${2}"
+VARS_DIR="${3}"
+OUTPUT_DIR="${4}"
 
-function main {
-    # recreate output dir
-    rm -rf "${OUTPUT_DIR}" && mkdir -p "${OUTPUT_DIR}"
-    
-    for FILE_PATH in files/*.yaml; do
-        FILE_NAME=$(basename "${FILE_PATH}")	
-        OUTPUT_FILE="${OUTPUT_DIR}/${FILE_NAME}"
-
-		_get_yaml "${FILE_NAME}" | gotpl "${FILE_PATH}" > "${OUTPUT_FILE}"
-		_check_for_unresolved "${OUTPUT_FILE}"
-		echo "-- generated file ${OUTPUT_FILE}:"
-		cat "${OUTPUT_FILE}"
-    done
+check_for_unresolved() {
+  local file="${1}"
+  if [[ $(grep -c "<no value>" "${file}") == "1" ]]; then
+    echo "error: found unresolved variable(s):" >&2
+    grep -Hn "<no value>" "${file}"
+    exit 1
+  fi
 }
 
-function _check_for_unresolved {
-    local FILE="${1}"
-    if [[ $(grep -c "<no value>" "${FILE}") == "1" ]]; then
-        echo "error: found unresolved variable(s):"
-        grep -Hn "<no value>" "${FILE}"
-        exit 1
-    fi
+get_yaml() {
+  local file=${1}
+  local base_file="${VARS_DIR}/base/${file}" 
+  local env_override_file="${VARS_DIR}/${ENV}/${file}" 
+
+  # merge if both files exist
+  if [[  -f "${base_file}" &&  -f "${env_override_file}" ]]; then 
+    yq merge --overwrite "${base_file}" "${env_override_file}" 
+    return
+  fi  
+
+  if [[ -f "${base_file}" ]]; then
+    cat "${base_file}"
+    return
+  fi
+
+  if [[ -f "${env_override_file}" ]]; then
+    cat "${env_override_file}"
+    return
+  fi
 }
 
-function _get_yaml {
-    local FILE=${1}
-	BASE_FILE="${VARS_DIR}/base/${FILE}" 
-	ENV_OVERRIDE_FILE="${VARS_DIR}/${ENV}/${FILE}" 
+print_help() {
+  cat <<EOF
+usage: naisplater [environment] [templates_dir] [variables_dir] [output_dir]
 
-	# merge if both files exist
-	if [[  -f "${BASE_FILE}" &&  -f "${ENV_OVERRIDE_FILE}" ]]; then 
-		yq merge --overwrite "${BASE_FILE}" "${ENV_OVERRIDE_FILE}" 
-		return
-    fi	
+environment           specifies which subdirectory in 'templates_dir' to merge/override yaml
+templates_dir         directory containing go template files
+variables_dir         directory containing yaml variable files. Environment specific overrides must go into sub dir variables_dir/<env>
+output_dir            folder to output processed templates
 
-	if [[ -f "${BASE_FILE}" ]]; then
-		cat "${BASE_FILE}"
-		return
-	fi
-
-	if [[ -f "${ENV_OVERRIDE_FILE}" ]]; then
-        cat "${ENV_OVERRIDE_FILE}"
-		return
-    fi
+EOF
 }
 
-main
+main() {
+
+  # TODO: use getopts and flags instead
+  if [[ "${#}" != 4 ]]; then
+    echo "error: must provide all four arguments" >&2
+	print_help
+	exit 1
+  fi 
+
+  # ensure output dir exists
+  mkdir -p "${OUTPUT_DIR}"
+  
+  for file_path in "${TEMPLATES_DIR}"/*.yaml; do
+    local file_name=$(basename "${file_path}")  
+    local output_file="${OUTPUT_DIR}/${file_name}"
+
+    get_yaml "${file_name}" | gotpl "${file_path}" > "${output_file}"
+    check_for_unresolved "${output_file}"
+    echo "-- generated file ${output_file}:"
+    cat "${output_file}"
+  done
+}
+
+main "$@"
